#!/usr/bin/env bash
[ "${FAKE_NO_VIRBR0:-0}" = 1 ] && exit 1
case "$*" in *virbr0*) echo "5: virbr0    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0\\       valid_lft forever preferred_lft forever" ;; esac
