#!/usr/bin/env bash
. "$(dirname "$0")/../_lib"
R="$F/ufw"; touch "$R"
case "$*" in
  status*) echo "Status: active"; cat "$R" ;;
  "allow from 192.168.122.0/24 to any port 11434 proto tcp") echo "11434/tcp ALLOW 192.168.122.0/24" >> "$R" ;;
  "delete allow from 192.168.122.0/24 to any port 11434 proto tcp") : > "$R" ;;
esac
